name: compas-3dec-dev
channels:
  - conda-forge
dependencies:
  - python >=3.9
  - pip
  - compas >=2.0
  - pip:
      - compas_dem @ git+https://github.com/BlockResearchGroup/compas_dem.git@main
      - -e .[dev,docs]
