def _quote(value):
    return "'{}'".format(str(value).replace("'", "''"))


def _format_number(value, precision):
    return "{:.{}f}".format(float(value), int(precision))


def render_geometry(analysis, precision=10):
    """Render rigid block geometry using the prepared model coordinates."""
    lines = [
        "; Generated by compas_3dec",
        "; COMPAS model {}".format(analysis.model_id),
    ]

    for block in sorted(analysis.blocks, key=lambda item: item["region"]):
        mesh = block["geometry"]
        faces = []
        for face in mesh.faces():
            vertices = list(mesh.face_vertices(face))
            vertices.reverse()
            coordinates = []
            for vertex in vertices:
                xyz = mesh.vertex_coordinates(vertex)
                coordinates.append(",".join(_format_number(value, precision) for value in xyz))
            faces.append("face " + " ".join(coordinates))

        group = block.get("group", "block")
        lines.append(
            "block create group {} poly {} r={}".format(
                _quote(group),
                " ".join(faces),
                int(block["region"]),
            )
        )

    identity_nodes = sorted({int(record[key]) for record in analysis.contact_block_pair_overrides for key in ("node_a", "node_b")})
    regions = {int(block["node"]): int(block["region"]) for block in analysis.blocks}
    for node in identity_nodes:
        lines.append(
            "block group {} slot {} range region {}".format(
                _quote("COMPAS_NODE_{}".format(node)),
                _quote("COMPAS_ID"),
                regions[node],
            )
        )

    return "\n".join(lines) + "\n"
